### ISSUE TITLE
create GitHub releases (or git tags at least)

### ISSUE THREAD

**Issue by koibtw** [rockorager/comlink#10]
hey. i'd love to package comlink for arch but there are no versions :(

**Comment by rockorager** [comment]
:wave: Thanks for packaging it!

I can tag a release for you to build off of. Let me know if there are any issues you come across - I'll be happy to make any changes needed to the build process to make packaging easier.

**Comment by rockorager** [comment]
https://github.com/rockorager/comlink/releases/tag/v0.1.1

Signed with [3C46ECF7BCA6BEA4054E2D583CD1C57266D24872](https://keys.openpgp.org/vks/v1/by-fingerprint/3C46ECF7BCA6BEA4054E2D583CD1C57266D24872)
