### ISSUE TITLE
Vaxis seems to leak log output in comlink

### ISSUE THREAD

**Issue by tristan957** [rockorager/comlink#2]
![image](https://github.com/user-attachments/assets/2b0da677-8aa3-4ce4-a0b6-1b0b724dfe55)

This image is just after launching comlink, and it waiting for me to input my 1Password credentials

**Comment by rockorager** [comment]
What type of build is this? If you use ReleaseSafe or ReleaseFast these
shouldn't show up

**Comment by tristan957** [comment]
ReleaseSafe

**Comment by rockorager** [comment]
Fixed in 675e235
